### ISSUE TITLE
About loss_opacity and loss_scales

### ISSUE THREAD

**Issue by ByChelsea** [cxh0519/threestudio-gaussiandreamer#2]
Hi, is [loss_opacity](https://github.com/cxh0519/threestudio-gaussiandreamer/blob/467d7c6e051ad7ecff7c33c9321f9f2df4ce4cab/system/gaussian_splatting.py#L95) and [loss_scales](https://github.com/cxh0519/threestudio-gaussiandreamer/blob/467d7c6e051ad7ecff7c33c9321f9f2df4ce4cab/system/gaussian_splatting.py#L103) derived from a certain paper? If not, what effects can they achieve?

Thank you for your explanation and clarification!

**Comment by cxh0519** [comment]
These regularization losses are inherited from threestudio-3dgs. You can make ablation studies to evaluate their effects, and these losses contribute small effects to the final results from my experience.
