### ISSUE TITLE
Difference in the camera setting

### ISSUE THREAD

**Issue by SuX97** [cxh0519/threestudio-gaussiandreamer#4]
Hi authors,

I noticed that in `gaussiandreamer_mvdream.yaml` the camera distance is set to `[0.8, 1.0]` and eval at 3.0, and fovy range is `[15, 60]`, elevation_range `[0, 30]`. However in `gaussiandreamer.yaml` it is distance=`1.5, 4.0` eval at 4.0, (default config) elevation=`-10, 60`.

I am wondering why is it set differently, is it because the `gaussiandreamer_mvdream.yaml` is default to be trained with LRM init, while `gaussiandreamer.yaml` is SHAP-E init, as the scale of the above two are different? But why are the fovy, az, elevation also different?

Looking forward to your reply!

**Comment by cxh0519** [comment]
The camera setting is inherited by the threestudio and threestudio-mvdream respectively. 
The initialization method causes no difference in camera settings, e.g., you can use LRM with SD2.1 and Shap-E with mvdream.
