### ISSUE TITLE
About the appearance of Gaussians.

### ISSUE THREAD

**Issue by Colezwhy** [cxh0519/threestudio-gaussiandreamer#9]
Hi, thank you for your great extension!
But when I am trying to use customized point clouds, the output of gaussiandreamer-threestudio will look not that appealing, even weird.
Could you please give some suggestions on how to improve this?
The example prompt is 'A sofa'
![image](https://github.com/cxh0519/threestudio-gaussiandreamer/assets/96565109/2d03be03-6f8a-42e0-a3b4-c3265ce82ba2)

**Comment by CM-BF** [comment]
Similar results. The generated objects contain this weird color pattern.

**Comment by CM-BF** [comment]
Hi @Colezwhy,

I have solved the issue. After tuning using different hyper parameters, I noticed that what really matters here is the point cloud initialization. After using the [fine-tuned Shap-E weights by Cap3D](https://huggingface.co/camenduru/GaussianDreamer/tree/main) suggested by [the original repo](https://github.com/hustvl/GaussianDreamer/tree/main), I got much better results. 

However, I still don't fully get the reason. Can you help to provide possible insights, @cxh0519 @codyreading? If I didn't get it wrong, I think the color initialization of the default Shap-E is problematic. 

### Original

#### 100 iters
![it100-0](https://github.com/user-attachments/assets/aa9fc95b-a243-48a9-8661-913ce826b009)

#### 1200 iters video
https://github.com/user-attachments/assets/ad38c519-21ba-434a-a72b-a861ced974f7

Note that I also tried to train it for 800 more iterations, i.e., 2000 iterations, the weird color pattern becomes even more sever. Any idea why?


### Fine-tuned Shap-E model

#### 100 iters
![it100-0](https://github.com/user-attachments/assets/933bcd02-9e04-4169-aef3-06e1734e971b)

#### 1200 iters video

https://github.com/user-attachments/assets/9b96d65d-b9f9-4843-9ce8-e64c52b8aeea


Best regards

**Comment by Colezwhy** [comment]
> Hi @Colezwhy,
> 
> I have solved the issue. After tuning using different hyper parameters, I noticed that what really matters here is the point cloud initialization. After using the [fine-tuned Shap-E weights by Cap3D](https://huggingface.co/camenduru/GaussianDreamer/tree/main) suggested by [the original repo](https://github.com/hustvl/GaussianDreamer/tree/main), I got much better results.
> 
> However, I still don't fully get the reason. Can you help to provide possible insights, @cxh0519 @codyreading? If I didn't get it wrong, I think the color initialization of the default Shap-E is problematic.
> 
> ### Original
> #### 100 iters
> ![it100-0](https://private-user-images.githubusercontent.com/35030752/348318343-aa9fc95b-a243-48a9-8661-913ce826b009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODQzNTMsIm5iZiI6MTcyMTE4NDA1MywicGF0aCI6Ii8zNTAzMDc1Mi8zNDgzMTgzNDMtYWE5ZmM5NWItYTI0My00OGE5LTg2NjEtOTEzY2U4MjZiMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAyNDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODgyMDk4NTNmMTUxZjczNGE4Y2NiYzVmOTYzZDk1MTA3ZDIwMDAzMmEwZTFlNmM2YWVmZjZkYTVkNWFkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DhxHs5w7al04VvfsHVHEcpwRRdX-8iLtYJ6I_SPiN94)
> 
> #### 1200 iters video
>  it1200-test.mp4 
> Note that I also tried to train it for 800 more iterations, i.e., 2000 iterations, the weird color pattern becomes even more sever. Any idea why?
> 
> ### Fine-tuned Shap-E model
> #### 100 iters
> ![it100-0](https://private-user-images.githubusercontent.com/35030752/348318860-933bcd02-9e04-4169-aef3-06e1734e971b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODQzNTMsIm5iZiI6MTcyMTE4NDA1MywicGF0aCI6Ii8zNTAzMDc1Mi8zNDgzMTg4NjAtOTMzYmNkMDItOWUwNC00MTY5LWFlZjMtMDZlMTczNGU5NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAyNDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDNhZWM4MTBjNWM4Y2M1ZTliODQxYTkwZjljNTQyMWU3NzdiNjNiMTQzYzRkZmQxNGYwNDMzMmQ2OThmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aHD9438t9rk7nCOF4Aw3hH-0STKBkmoF9jsnMITIqZE)
> 
> #### 1200 iters video
>  it1200-test.mp4 
> Best regards

Thank you for your results and kind sharing, and I am using customized point clouds thus it might be a more fussy thing to tune the parameters.
